Document: ltsp-pnp
Title: Debian ltsp-pnp Manual
Author: <insert document author here>
Abstract: This manual describes what ltsp-pnp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ltsp-pnp/ltsp-pnp.sgml.gz

Format: postscript
Files: /usr/share/doc/ltsp-pnp/ltsp-pnp.ps.gz

Format: text
Files: /usr/share/doc/ltsp-pnp/ltsp-pnp.text.gz

Format: HTML
Index: /usr/share/doc/ltsp-pnp/html/index.html
Files: /usr/share/doc/ltsp-pnp/html/*.html
